# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/asus/Desktop/project_proje/project_proje.cache/wt [current_project]
set_property parent.project_path C:/Users/asus/Desktop/project_proje/project_proje.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/asus/Desktop/project_proje/project_proje.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/servo.vhd
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/Range_sensor_2.vhd
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/Range_sensor_1.vhd
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/Multiplexer.vhd
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/counter.vhd
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/Buzzer.vhd
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/anode_decoder.vhd
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/BCD.vhd
  C:/Users/asus/Desktop/project_proje/project_proje.srcs/sources_1/new/Top_Module.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/asus/Desktop/project_proje/project_proje.srcs/constrs_1/new/proje_const.xdc
set_property used_in_implementation false [get_files C:/Users/asus/Desktop/project_proje/project_proje.srcs/constrs_1/new/proje_const.xdc]


synth_design -top top_module -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_module.dcp

catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
